server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${HW2_POSTGRESQL_SERVICE_HOST:test}/${POSTGRES_DB:test}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
