apiVersion: batch/v1
kind: Job
metadata:
  name: "hw2app-postgres-job"
spec:
  template:
    metadata:
      name: "hw2app-postgres-job"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "otus_hw2"
          command:
            - sh
            - "-c"
            - |
              psql postgres://otus_hw2:otus_hw2@hw2-postgresql/otus_hw2 <<'EOF'
                DROP SCHEMA public CASCADE;
                CREATE SCHEMA public;
                create table if not exists users (id serial primary key, first_name varchar(100), last_name varchar(100), email varchar(50), phone varchar(25));
                alter table users owner to otus_hw2;
