apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.global.postgresql.auth.database | b64enc }}
  POSTGRES_USER: {{ .Values.global.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
